### ISSUE TITLE
Got a hex logo?

### ISSUE THREAD

**Issue by RaymondBalise** [EvaMaeRey/flipbookr#15]
I am writing a talk covering R Markdown and related tools, and I wanted to show flipbookr.  Do you have a hex logo (sticker) to go with the package?  If so can you add it to the repo so I can tag the slides that feature flipbookr with your logo?

Thanks a bunch, your work is greatly appreciated.

**Comment by EvaMaeRey** [comment]
Hi.  We don't have one yet!  Something to be thinking about...  If you are willing to share your talk materials (or just the part about flipbookr would be really happy to hear more.)  For example, have you created your first flipbook?  How was the experience?  Thanks!

**Comment by RaymondBalise** [comment]
I don’t know how to send direct messages via github... Send me an email at my last name at miami.edu and we can gab.

Ray


On Feb 16, 2020, at 4:47 PM, Gina Reynolds <notifications@github.com> wrote:

﻿

Hi. We don't have one yet! Something to be thinking about... If you are willing to share your talk materials (or just the part about flipbookr would be really happy to hear more.) For example, have you created your first flipbook? How was the experience? Thanks!

**Comment by EvaMaeRey** [comment]
working on it.
