### ISSUE TITLE
Title on a "reveal" slide

### ISSUE THREAD

**Issue by droglenc** [EvaMaeRey/flipbookr#17]
Dr. Reynolds,

First, think you very much for flipbookr. It looks to be a wonderful tool!! 

I do have a couple of questions that I will pose as issues here. My first question is whether it is possible to have a "title" on the slides that are "revealing" the code. I do not see that in any of the example flipbooks. Essentially I would like to have a slide that looks like this (I have a minimal reproducible example I could give you, but I can't figure out how to include it here without Github rendering the rmarkdown code) ...

```
---

# I would like to include a title here!

`r chunk_reveal("cars", break_type = "auto")`

---
```

**Comment by droglenc** [comment]
I should have noted that the reveal slide looks roughly like this ...

---
I would like to include a title here!

class: split-40 count: false

cars

**Comment by EvaMaeRey** [comment]
Hi @droglenc, I have thought about the title a few times myself, so I will let you know soon if I get to implementing it..  I think this might involve changing the side-by-side approach to one that is more like @gadenbuie's   https://www.garrickadenbuie.com/blog/decouple-code-and-output-in-xaringan-slides/  Currently the css is different  - columns defined, not .pull-left and .pull-right.  This probably doesn't explain very clearly.  Just some notes to myself.  But I have been thinking about it, and appreciate your interest in this.

**Comment by EvaMaeRey** [comment]
Regarding left_assign.  It sounds not hard to implement, but I guess it is a little lower priority in my mind.   Out of curiosity, I'd be interested to know how you found out about flipbookr. Thanks!

**Comment by droglenc** [comment]
Thank you. I don't remember how I first heard of flipbookr. I know that I watched the video of your UserR talk because I am interested in teaching R. However, I have not had a need to for such a step-by-step (the revealing) approach until I was just approved to teach (essentially) a ggplot2 course. I am now preparing materials for that. We will see how it goes in a couple of weeks.

Thanks again for your creation of the package and your response.

**Comment by EvaMaeRey** [comment]
There is now an argument for title = "" in chunk_reveal, if you want to update your {flipbookr} package by reinstalling.   You will have to enter the markdown hierarchy if you want that, so title = "# My Title" should give you a nice big bold title.

**Comment by droglenc** [comment]
Gina .... sorry for the delay. Thank you. I also like the other new features.
