### ISSUE TITLE
Comments Before Code when Using `left_assign=TRUE`

### ISSUE THREAD

**Issue by droglenc** [EvaMaeRey/flipbookr#18]
Related to my previous question (#17 ) I would like to have a comment before my code that will ultimately be revealed. This seems to work OK unless I use `left_assign=TRUE`, which is my preference. So this chunk ...

```
## I hope to do this
p <- cars %>%
  filter(speed > 4) %>%
  ggplot() +
  aes(x = speed) +
  aes(y = dist) + #BREAK
  geom_point(
    alpha = .3, #BREAK2
    color = "blue" #BREAK3
    ) + #BREAK
  aes(size = speed) #BREAK
```

... when used like this ...

```
`r chunk_reveal("cars", break_type = "auto", left_assign=TRUE)`
```

... reveals a slide that looks roughly like that below (and now graph in the right column, only an NA).

---
```
## I hope to do this
p <- cars
NA
```

**Comment by EvaMaeRey** [comment]
Not planning on doing exactly this, but might have mode to print only most recently created object as end of partial code builds.

**Comment by EvaMaeRey** [comment]
This should work now.

**Comment by EvaMaeRey** [comment]
Please let me know if you have a chance to give it a try!

**Comment by droglenc** [comment]
This seems to work now. Thank you!!!

**Comment by EvaMaeRey** [comment]
Great!! Thanks for letting me know!
