### ISSUE TITLE
Code on top, output below

### ISSUE THREAD

**Issue by rfaridi** [EvaMaeRey/flipbookr#20]
I know in most of the cases side my side revelation of code output is preferable. But in some cases , it may be needed to show code on top and output below. Particularly in cases where the output has a large width and the full width needs to be displayed.  Is it possible in the current framework of flipbookr?

**Comment by EvaMaeRey** [comment]
This is not currently supported.  However, you might try some adjustment to output width relative to code size.  Allowing width adjustment is a new feature, not yet documented, but there is an example in the new template.

**Comment by marcmtk** [comment]
I managed to hack together something resembling a solution (for my limited use case).
in define_css i exchanged ```normalized_widths <- active_in_100 * widths/sum(widths)```  with ```normalized_widths <- widths``` then called chunk_reveal with ```chunk_reveal("chunk_name", float = "none", widths = c(100, 100))```
![fig](https://user-images.githubusercontent.com/7996691/94347437-6eac0a00-0034-11eb-8d2f-e5807073cb31.png)

```

**Comment by EvaMaeRey** [comment]
This is my working example from the "A minimal flipbook" template.   I'd favor a solution such that output area is fixed (now output moves lower to allow more lines of code).  I think widths likely don't need to be defined (default should work), but I'm not going to check it our just now. 

---

`r chunk_reveal("top_bottom", title = "## top/bottom display - experimental", widths = c(24, 75), float = "top")`

```{r top_bottom, include=F}
cars %>% 
  slice(1:10) %>% 
  t()
```
