### ISSUE TITLE
Example flipbook to powerpoint

### ISSUE THREAD

**Issue by brshallo** [EvaMaeRey/flipbookr#33]
I made an example for converting a flipbook to a powerpoint (could be useful for `flipbookr` documentation for people looking to embed a flipbook directly into a pptx). Approach works similar to that described for creating gifs in EvaMaeRey/flipbookr#22 but now uses @davidgohel [officer](https://github.com/davidgohel/officer) package to embed images into the .pptx. I added the example to the same repo I'd used for documenting EvaMaeRey/flipbookr#22. Specifically, see new script [brshallo/flipbookr-gifs-examples/render-flipbook-ppt-example.R](render-flipbook-ppt-example.R) , copy of code:

```r
filepath <- fs::path_ext_remove("example-r4ds.Rmd")
filepath_pdf <- fs::path_ext_set(filepath, "pdf")
filepath_pptx <- fs::path_ext_set(filepath, "pptx")

pagedown::chrome_print(filepath) # run if have not already created pdf

screen_imgs <- pdftools::pdf_convert(pdf = filepath_pdf, format = "png", verbose = FALSE)

library(officer)
library(tidyverse)

doc <- read_pptx()
for (i in seq_along(screen_imgs)){
  doc <- doc %>%
    add_slide(layout = "Blank", master="Office Theme") %>% 
    ph_with(value = external_img(screen_imgs[[i]]), 
            location = ph_location_fullsize() ) 
}

print(doc, filepath_pptx) 
```

Screenshot of resulting .pptx:
![image](https://user-images.githubusercontent.com/30487784/92028138-8e039000-ed31-11ea-9b14-99065bdd757c.png)

Comments:

* Rather than using `magick::image_read_pdf()` (as had done for gif in EvaMaeRey/flipbookr#22), I used `pdftools::pdf_convert()`. This was because I was getting an `Error in UseMethod("ph_with", value) : 
  no applicable method for 'ph_with' applied to an object of class "c('bitmap', 'rgba')"` when trying to reference the images in `officer::ph_with()`. This was surprising as thought bitmap would be supported based on davidgohel/officer#101 (may look into more...)
* With defaults, screenshots get slightly squeezed
* Should probably have .png images created go to a temp folder (or get `screen_imgs <- magick::image_read_pdf()` to work with `officer::ph_with(value = screen_imgs[[i]], 
            location = ph_location_fullsize())`)
* Link to initial [tweet](https://twitter.com/brshallo/status/1300954275737198592)

**Comment by davidgohel** [comment]
> [...] This was surprising as thought bitmap would be supported [...] 

have a look at `external_img()` and `ph_with` documentation: https://davidgohel.github.io/officer/reference/ph_with.html

> With defaults, screenshots get slightly squeezed

You need to know the width/height of the image and provide them to `external_img()`

**Comment by EvaMaeRey** [comment]
Moving to xaringanPrinter package.
