### ISSUE TITLE
Errors when strings contain square brackets

### ISSUE THREAD

**Issue by actuarialvoodoo** [EvaMaeRey/flipbookr#37]
If I have a string argument with a square bracket in a code chunk I'd like to step through I get html formatting in the slide instead of the desired behavior. I came across this while using regular expressions in an example to my colleagues, but I've attached the simplest reprex I could come up with.

[reprex_issues.Rmd.gz](https://github.com/EvaMaeRey/flipbookr/files/5359677/reprex_issues.Rmd.gz)

**Comment by EvaMaeRey** [comment]
Demos for regular expressions sounds like a good idea. Thank you for alerting me to this problem.  flipbookr counts parentheses (and brackets) to make sure they are balanced in making the decision whether to pause or not at the end of a line.  Probably not a super quick fix to address this case.  But I'll start thinking about it.

**Comment by actuarialvoodoo** [comment]
That explains why regular expressions with matched parenthesis didn't cause a problem.

**Comment by EvaMaeRey** [comment]
I'm gonna close this for now, as I see it as a corner case.  Maybe fix in future.
