### ISSUE TITLE
How to add text to a slide

### ISSUE THREAD

**Issue by PMassicotte** [EvaMaeRey/flipbookr#42]
I have this simple piece of code that works fine.

```r
```{r, chunk1, include = FALSE}
ggplot(mpg, aes(x = displ, y = cty)) +
  geom_point() +
  facet_wrap(~class)
```

```r
`r chunk_reveal(chunk_name = "chunk1", title = "# my title")`
```

However, I can not find a to add some static text at the top (or wherever) on the slide. Is it currently possible?

**Comment by EvaMaeRey** [comment]
You want it to say "my title" on each frame of the flipbook? But it is not appearing?

**Comment by PMassicotte** [comment]
In fact, I would like to add text either above or below the code. For example, 1-2 sentences explaining the code. 

![image](https://user-images.githubusercontent.com/4519221/103463843-73502080-4cfd-11eb-9369-afb4c3340424.png)

**Comment by EvaMaeRey** [comment]
I see.  You are be able to include code comments.  I will think about subtitle/discussion argument which is what you seem interested in.

For now, you might hack the title a bit like this:

`r chunk_reveal("my_cars", title = "### My title \nSome discussion about the figure... ")`
