### ISSUE TITLE
Change reference in gif to xaringanBuilder

### ISSUE THREAD

**Issue by brshallo** [EvaMaeRey/flipbookr#45]
You might change the reference about building a preview of a gif [here](https://github.com/EvaMaeRey/flipbookr/blob/fc175bc8aaf39b0fe4a9937a3ddd603166f85c21/inst/rmarkdown/templates/most-features/skeleton/skeleton.Rmd#L958) to instead use [xaringanBuilder](https://github.com/jhelvy/xaringanBuilder) (or might perhaps leave as is and just add a note referencing {xaringanBuilder} there as option for different output formats...)

Pros:

* {xaringanBuilder} has a few checks in place that may be useful
* Would cue user to easy ways to output to other formats in addition to gif (e.g. powerpoint)

Con:

* {xaringanBuilder} is not yet on CRAN and has (I presume) more dependencies than {magick} (but given {flipbookr} is also not on CRAN this may not be too much of a concern.

**Comment by EvaMaeRey** [comment]
Hi Brian!  would you consider submitting a pull request?
