### ISSUE TITLE
@examples require a value

### ISSUE THREAD

**Issue by dewittpe** [EvaMaeRey/flipbookr#5]
When building the package from commit af7cffb the warning "@examples require a value" came up several times.  This seems to be result of two things:

1. the `@examples` section of the roxygen comments in R/base_parse_reveal_xarignan.R are empty.
2. the `local_code` object is not exported.

**Comment by EvaMaeRey** [comment]
I'm not sure what to think about examples for non exported functions.  I kind of like to have them nearby, but I don't want to do more exported functions than is needed.
